version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=random13131
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - bharat-fd-faqs_pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  backend:
    container_name: bharat-fd-backend
    build: ./server
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    volumes:
      - .:/backend
    depends_on:
      - redis
      - db

  admin:
    container_name: react-admin
    build: ./admin
    ports:
      - 3000:80
    depends_on:
      - backend

volumes:
  bharat-fd-faqs_pgdata:
