version: '3.8'

services:
  db:
    container_name: bharat-fd-postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=random13131
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - bharat-fd-faqs_pgdata:/var/lib/postgresql/data


  redis:
    container_name: redis_container
    image: redis
    ports:
      - 6379:6379


volumes:
  bharat-fd-faqs_pgdata:
      